<?php
/** @package D025c936::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("PackageMap.php");

/**
 * PackageDAO provides object-oriented access to the package table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package D025c936::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class PackageDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var date */
	public $ShipDate;

	/** @var date */
	public $ShipTime;

	/** @var int */
	public $CustomerId;

	/** @var string */
	public $TrackingNumber;

	/** @var string */
	public $Description;

	/** @var string */
	public $Service;

	/** @var string */
	public $Destination;


	/**
	 * Returns the foreign object based on the value of CustomerId
	 * @return Customer
	 */
	public function GetCustomer()
	{
		return $this->_phreezer->GetManyToOne($this, "p_customer");
	}

	/**
	 * Returns the foreign object based on the value of Service
	 * @return Service
	 */
	public function GetService()
	{
		return $this->_phreezer->GetManyToOne($this, "p_service_code");
	}


}
?>