<?php
/** @package D025c936::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("PurchaseMap.php");

/**
 * PurchaseDAO provides object-oriented access to the purchase table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package D025c936::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class PurchaseDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $StatusCodeId;

	/** @var int */
	public $Quantity;

	/** @var string */
	public $Description;


	/**
	 * Returns the foreign object based on the value of StatusCodeId
	 * @return StatusCode
	 */
	public function GetStatusCode()
	{
		return $this->_phreezer->GetManyToOne($this, "p_status_code");
	}


}
?>